### ISSUE TITLE
Docs - Increase verbosity of steps

### ISSUE THREAD

**Issue by ChrisPhillips-cminion** [IBM/datapower-operator-doc#12]
https://ibm.github.io/datapower-operator-doc/troubleshooting/stale-webhooks/

Step 3 says `Repeat Steps 1 and 2, for the ValidatingWebhookConfiguration resource.`

Can we please modify this to include full command examples as I miss read this step when I scan read the instructions.

**Comment by aharbis** [comment]
I'm including these changes in PR #11 for our `1.0.1` release.
